### PR TITLE
My/dedup

### PR DESCRIPTION
**Pull request by 7eggert**
(My first push request on github, hope I'm doing it right)

Two commits:

- Add -S option to not clutter the screen with skipped / ignored files
 (also --no-print-skipped)
- document newest to be the default dedup strategy

### CODE REVIEW

**Comment by trapexit** [comment]
I'd prefer the `-S` to be part of verbose. Maybe just make the verbose check when ignoring `if verbose >=2` rather than `if verbose`?

Typically you should submit separate pull requests for logically separate things. Not a big deal here but good practice. Also it looks like you made these changes one with your user and one with root. Shouldn't be doing this stuff as root but in the least you should setup git properly so your name and email are set appropriately.

**Comment by trapexit** [comment]
I'm working on a new version of dedup so I can incorporate these changes but I'm happy to accept a PR so long as you address the above.

**Comment by 7eggert** [comment]
closed because of being replaced

**Comment by trapexit** [comment]
You don't need to close a PR. You can change your branch as you wish then force push it.

**Pull request closed without merging**
